// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: metrics.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metrics) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metrics) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Metrics) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Metrics) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Get one metric by name and type
type GetMetricByNameAndTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricByNameAndTypeRequest) Reset() {
	*x = GetMetricByNameAndTypeRequest{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricByNameAndTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricByNameAndTypeRequest) ProtoMessage() {}

func (x *GetMetricByNameAndTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricByNameAndTypeRequest.ProtoReflect.Descriptor instead.
func (*GetMetricByNameAndTypeRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetricByNameAndTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMetricByNameAndTypeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetMetricByNameAndTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metrics               `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricByNameAndTypeResponse) Reset() {
	*x = GetMetricByNameAndTypeResponse{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricByNameAndTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricByNameAndTypeResponse) ProtoMessage() {}

func (x *GetMetricByNameAndTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricByNameAndTypeResponse.ProtoReflect.Descriptor instead.
func (*GetMetricByNameAndTypeResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *GetMetricByNameAndTypeResponse) GetMetric() *Metrics {
	if x != nil {
		return x.Metric
	}
	return nil
}

// Get all metrics
type GetAllMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMetricsRequest) Reset() {
	*x = GetAllMetricsRequest{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMetricsRequest) ProtoMessage() {}

func (x *GetAllMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetAllMetricsRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

type GetAllMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       map[string]*Metrics    `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMetricsResponse) Reset() {
	*x = GetAllMetricsResponse{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMetricsResponse) ProtoMessage() {}

func (x *GetAllMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetAllMetricsResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllMetricsResponse) GetMetrics() map[string]*Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Update metric
type UpdateMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metrics               `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricRequest) Reset() {
	*x = UpdateMetricRequest{}
	mi := &file_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricRequest) ProtoMessage() {}

func (x *UpdateMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMetricRequest) GetMetric() *Metrics {
	if x != nil {
		return x.Metric
	}
	return nil
}

type UpdateMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metrics               `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricResponse) Reset() {
	*x = UpdateMetricResponse{}
	mi := &file_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricResponse) ProtoMessage() {}

func (x *UpdateMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMetricResponse) GetMetric() *Metrics {
	if x != nil {
		return x.Metric
	}
	return nil
}

// Update batch metrics
type UpdateBatchMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        []*Metrics             `protobuf:"bytes,1,rep,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBatchMetricsRequest) Reset() {
	*x = UpdateBatchMetricsRequest{}
	mi := &file_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBatchMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBatchMetricsRequest) ProtoMessage() {}

func (x *UpdateBatchMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBatchMetricsRequest.ProtoReflect.Descriptor instead.
func (*UpdateBatchMetricsRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBatchMetricsRequest) GetMetric() []*Metrics {
	if x != nil {
		return x.Metric
	}
	return nil
}

type UpdateBatchMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBatchMetricsResponse) Reset() {
	*x = UpdateBatchMetricsResponse{}
	mi := &file_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBatchMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBatchMetricsResponse) ProtoMessage() {}

func (x *UpdateBatchMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBatchMetricsResponse.ProtoReflect.Descriptor instead.
func (*UpdateBatchMetricsResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBatchMetricsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Ping gRPC method
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{9}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\ametrics\"Y\n" +
	"\aMetrics\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"C\n" +
	"\x1dGetMetricByNameAndTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"J\n" +
	"\x1eGetMetricByNameAndTypeResponse\x12(\n" +
	"\x06metric\x18\x01 \x01(\v2\x10.metrics.MetricsR\x06metric\"\x16\n" +
	"\x14GetAllMetricsRequest\"\xac\x01\n" +
	"\x15GetAllMetricsResponse\x12E\n" +
	"\ametrics\x18\x01 \x03(\v2+.metrics.GetAllMetricsResponse.MetricsEntryR\ametrics\x1aL\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.metrics.MetricsR\x05value:\x028\x01\"?\n" +
	"\x13UpdateMetricRequest\x12(\n" +
	"\x06metric\x18\x01 \x01(\v2\x10.metrics.MetricsR\x06metric\"@\n" +
	"\x14UpdateMetricResponse\x12(\n" +
	"\x06metric\x18\x01 \x01(\v2\x10.metrics.MetricsR\x06metric\"E\n" +
	"\x19UpdateBatchMetricsRequest\x12(\n" +
	"\x06metric\x18\x01 \x03(\v2\x10.metrics.MetricsR\x06metric\"4\n" +
	"\x1aUpdateBatchMetricsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xac\x03\n" +
	"\x0eMetricsService\x12N\n" +
	"\rGetAllMetrics\x12\x1d.metrics.GetAllMetricsRequest\x1a\x1e.metrics.GetAllMetricsResponse\x12i\n" +
	"\x16GetMetricByNameAndType\x12&.metrics.GetMetricByNameAndTypeRequest\x1a'.metrics.GetMetricByNameAndTypeResponse\x12K\n" +
	"\fUpdateMetric\x12\x1c.metrics.UpdateMetricRequest\x1a\x1d.metrics.UpdateMetricResponse\x12]\n" +
	"\x12UpdateBatchMetrics\x12\".metrics.UpdateBatchMetricsRequest\x1a#.metrics.UpdateBatchMetricsResponse\x123\n" +
	"\x04Ping\x12\x14.metrics.PingRequest\x1a\x15.metrics.PingResponseB\vZ\t./metricsb\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_metrics_proto_goTypes = []any{
	(*Metrics)(nil),                        // 0: metrics.Metrics
	(*GetMetricByNameAndTypeRequest)(nil),  // 1: metrics.GetMetricByNameAndTypeRequest
	(*GetMetricByNameAndTypeResponse)(nil), // 2: metrics.GetMetricByNameAndTypeResponse
	(*GetAllMetricsRequest)(nil),           // 3: metrics.GetAllMetricsRequest
	(*GetAllMetricsResponse)(nil),          // 4: metrics.GetAllMetricsResponse
	(*UpdateMetricRequest)(nil),            // 5: metrics.UpdateMetricRequest
	(*UpdateMetricResponse)(nil),           // 6: metrics.UpdateMetricResponse
	(*UpdateBatchMetricsRequest)(nil),      // 7: metrics.UpdateBatchMetricsRequest
	(*UpdateBatchMetricsResponse)(nil),     // 8: metrics.UpdateBatchMetricsResponse
	(*PingRequest)(nil),                    // 9: metrics.PingRequest
	(*PingResponse)(nil),                   // 10: metrics.PingResponse
	nil,                                    // 11: metrics.GetAllMetricsResponse.MetricsEntry
}
var file_metrics_proto_depIdxs = []int32{
	0,  // 0: metrics.GetMetricByNameAndTypeResponse.metric:type_name -> metrics.Metrics
	11, // 1: metrics.GetAllMetricsResponse.metrics:type_name -> metrics.GetAllMetricsResponse.MetricsEntry
	0,  // 2: metrics.UpdateMetricRequest.metric:type_name -> metrics.Metrics
	0,  // 3: metrics.UpdateMetricResponse.metric:type_name -> metrics.Metrics
	0,  // 4: metrics.UpdateBatchMetricsRequest.metric:type_name -> metrics.Metrics
	0,  // 5: metrics.GetAllMetricsResponse.MetricsEntry.value:type_name -> metrics.Metrics
	3,  // 6: metrics.MetricsService.GetAllMetrics:input_type -> metrics.GetAllMetricsRequest
	1,  // 7: metrics.MetricsService.GetMetricByNameAndType:input_type -> metrics.GetMetricByNameAndTypeRequest
	5,  // 8: metrics.MetricsService.UpdateMetric:input_type -> metrics.UpdateMetricRequest
	7,  // 9: metrics.MetricsService.UpdateBatchMetrics:input_type -> metrics.UpdateBatchMetricsRequest
	9,  // 10: metrics.MetricsService.Ping:input_type -> metrics.PingRequest
	4,  // 11: metrics.MetricsService.GetAllMetrics:output_type -> metrics.GetAllMetricsResponse
	2,  // 12: metrics.MetricsService.GetMetricByNameAndType:output_type -> metrics.GetMetricByNameAndTypeResponse
	6,  // 13: metrics.MetricsService.UpdateMetric:output_type -> metrics.UpdateMetricResponse
	8,  // 14: metrics.MetricsService.UpdateBatchMetrics:output_type -> metrics.UpdateBatchMetricsResponse
	10, // 15: metrics.MetricsService.Ping:output_type -> metrics.PingResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
