package storage

const (
	createTables = `CREATE TABLE IF NOT EXISTS metrics (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		type TEXT NOT NULL,
		name TEXT NOT NULL,
		value DOUBLE PRECISION,
		delta BIGINT,
		timestamp TIMESTAMP NOT NULL
	);
	CREATE INDEX IF NOT EXISTS idx_metrics_name ON metrics (name);`
	getMetricByName = `SELECT name, type, value, delta FROM metrics WHERE name = $1;`
	getAllMetrics   = `SELECT name, type, value, delta FROM metrics;`
	insertMetrics   = `INSERT INTO metrics (type, name, value, delta, timestamp)
						VALUES ($1, $2, $3, $4, $5)`
)
