package storage

const (
	// Создание базовой структуры таблиц
	createTables = `CREATE TABLE IF NOT EXISTS metrics (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		type TEXT NOT NULL,
		name TEXT NOT NULL,
		value DOUBLE PRECISION,
		delta BIGINT,
		timestamp TIMESTAMP NOT NULL,

		CONSTRAINT metrics_name_type_unique UNIQUE (name, type)
	);
	CREATE INDEX IF NOT EXISTS idx_metrics_name ON metrics (name);`
	// Получение метрик по имени
	getMetricByName = `SELECT name, type, value, delta FROM metrics WHERE name = $1 ORDER BY timestamp DESC LIMIT 1;`
	// Получение всех метрик
	getAllMetrics = `SELECT name, type, value, delta FROM metrics;`
	// Вставка новой метрики в таблицу
	insertMetrics = `INSERT INTO metrics (type, name, value, delta, timestamp)
						VALUES ($1, $2, $3, $4, $5)`
	// Вставка метрик по delta
	insertCounterMetrics = `INSERT INTO metrics (type, name, delta, timestamp)
						VALUES ($1, $2, $3, $4) ON CONFLICT (name, type) DO UPDATE SET delta = $3`
	// Вставка метрик по value
	insertGaugeMetrics = `INSERT INTO metrics (type, name, value, timestamp) 
						VALUES ($1, $2, $3, $4) ON CONFLICT (name, type) DO UPDATE SET value = $3`
)
